"""H3: the four-family matrix against a common target-specific control.

The direct test of whether the apparent relational structure in the
complementary-control matrix was generated by the control design. Every
constant is imported from ``run_natural_transfer`` rather than restated, so
"identical except the control definition" is structural: families, tokenizer,
vocabulary, model shape, learning rate, chunk budgets, batch size, seeds and
evaluation offsets cannot drift between the two designs.

    treatment   source D_i  ->  target D_j
    control     common N_j  ->  target D_j        (identical for every i)

``N_j`` is a function of the target and the seed alone. Its trajectory is
computed **once per (target, seed)** and reused by all three sources, so the
invariant is enforced by construction rather than by convention, and each
unit records the control stream's hash so cross-source identity is checkable
after the fact.

Trajectory arithmetic: 12 treatment arms plus 4 control arms per seed, so 48
trajectories over 3 seeds against the complementary design's 72. The cheaper
design is also the more sharply identified one.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

import equinox as eqx
import jax.numpy as jnp
import jax.random as jr
import numpy as np
import optax

sys.path.insert(0, str(Path(__file__).resolve().parent))

from run_natural_transfer import (  # noqa: E402
    BATCH, CHUNKS_PER_PHASE, D_MODEL, EVAL_CHUNKS, LR, N_HEADS, N_LAYERS, OFFSETS,
    SEQ_LEN, USABLE_FAMILIES, _eval_loss, _step, _train, common_control_chunks,
    family_chunks, load_frozen)

from dsi.artifacts import code_version, utc_now  # noqa: E402
from dsi.model import ModelConfig, init_model  # noqa: E402
from dsi.natural import chunk_documents  # noqa: E402
from dsi.stats import transfer_effect  # noqa: E402


def _hash(chunks: np.ndarray) -> str:
    return hashlib.blake2b(np.ascontiguousarray(chunks).tobytes(), digest_size=8).hexdigest()


def _setup(state: dict, target: int, seed: int):
    vocabulary = state["vocabulary"]
    model_config = ModelConfig(vocab_size=vocabulary.size, d_model=D_MODEL,
                               n_layers=N_LAYERS, n_heads=N_HEADS, d_ff=4 * D_MODEL,
                               max_len=SEQ_LEN)
    optimizer = optax.adamw(optax.constant_schedule(LR), weight_decay=0.01)
    eval_chunks = jnp.asarray(chunk_documents(
        state["documents"][("val", target)], vocabulary, SEQ_LEN, seed=0)[:EVAL_CHUNKS])
    # Depends on (target, seed) only, so every arm with this target consumes
    # the identical target stream in the identical order.
    target_stream = family_chunks(state, target, CHUNKS_PER_PHASE, seed + 1000)
    return model_config, optimizer, eval_chunks, target_stream


def _trajectory(prefix, model_config, optimizer, eval_chunks, target_stream, seed):
    """One arm: source phase, then the target phase with the t=0 evaluation."""
    n_steps = CHUNKS_PER_PHASE // BATCH
    marks = {int(round(o * n_steps)) for o in OFFSETS}
    model = init_model(model_config, jr.fold_in(jr.key(seed), 1))     # shared init
    fingerprint = float(jnp.sum(model.embed.weight))
    opt_state = optimizer.init(eqx.filter(model, eqx.is_inexact_array))
    model, opt_state = _train(model, opt_state, optimizer, prefix)

    curve = [{"step": 0, "offset": 0.0, "loss": float(_eval_loss(model, eval_chunks))}]
    for step in range(1, n_steps + 1):
        batch = jnp.asarray(target_stream[(step - 1) * BATCH: step * BATCH])
        model, opt_state, _ = _step(model, opt_state, batch, optimizer)
        if step in marks:
            curve.append({"step": step, "offset": step / n_steps,
                          "loss": float(_eval_loss(model, eval_chunks))})
    return curve, fingerprint


def control_arm(target: int, seed: int, out: Path, state: dict) -> dict:
    """The common control for one target. Computed once, reused by every source."""
    path = out / "controls" / f"f{target}__seed{seed}.json"
    if path.exists():
        return json.loads(path.read_text())
    started = time.time()
    model_config, optimizer, eval_chunks, target_stream = _setup(state, target, seed)
    stream, families = common_control_chunks(state, target, CHUNKS_PER_PHASE, seed)
    curve, fingerprint = _trajectory(stream, model_config, optimizer, eval_chunks,
                                     target_stream, seed)
    payload = {"target": target, "seed": seed, "control_families": families,
               "control_stream_hash": _hash(stream), "lm_tokens": int(stream.size),
               "init_fingerprint": fingerprint, "curve": curve,
               "seconds": time.time() - started,
               "code_version": code_version(), "recorded_at": utc_now()}
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp"); tmp.write_text(json.dumps(payload, indent=2) + "\n")
    tmp.replace(path)
    return payload


def treatment_arm(source: int, target: int, seed: int, out: Path, state: dict) -> dict:
    path = out / "treatments" / f"f{source}__to__f{target}__seed{seed}.json"
    if path.exists():
        return json.loads(path.read_text())
    started = time.time()
    model_config, optimizer, eval_chunks, target_stream = _setup(state, target, seed)
    stream = family_chunks(state, source, CHUNKS_PER_PHASE, seed)
    curve, fingerprint = _trajectory(stream, model_config, optimizer, eval_chunks,
                                     target_stream, seed)
    payload = {"source": source, "target": target, "seed": seed,
               "source_stream_hash": _hash(stream), "lm_tokens": int(stream.size),
               "init_fingerprint": fingerprint, "curve": curve,
               "seconds": time.time() - started,
               "code_version": code_version(), "recorded_at": utc_now()}
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp"); tmp.write_text(json.dumps(payload, indent=2) + "\n")
    tmp.replace(path)
    return payload


def assemble(source: int, target: int, seed: int, out: Path, state: dict) -> dict:
    control = control_arm(target, seed, out, state)
    treatment = treatment_arm(source, target, seed, out, state)
    if control["lm_tokens"] != treatment["lm_tokens"]:
        raise AssertionError(
            f"control {control['lm_tokens']} != treatment {treatment['lm_tokens']} "
            "LM tokens; arms are not exposure-matched")
    if control["init_fingerprint"] != treatment["init_fingerprint"]:
        raise AssertionError("arms did not share the initialization")

    t = [r["offset"] for r in control["curve"]]
    ctrl = [r["loss"] for r in control["curve"]]
    treat = [r["loss"] for r in treatment["curve"]]
    payload = {
        "source": source, "target": target, "seed": seed, "control": "common_N_j",
        "control_families": control["control_families"],
        "control_stream_hash": control["control_stream_hash"],
        "source_stream_hash": treatment["source_stream_hash"],
        "lm_tokens_source": treatment["lm_tokens"],
        "lm_tokens_control": control["lm_tokens"],
        "T_aulc": transfer_effect(t, ctrl, treat, normalize=True),
        "T_aulc_rate_only": transfer_effect(t, ctrl, treat, normalize=True,
                                            baseline_correct=True),
        "head_start": ctrl[0] - treat[0],
        "endpoint": ctrl[-1] - treat[-1],
        "curve_control": control["curve"], "curve_treatment": treatment["curve"],
        "code_version": code_version(), "recorded_at": utc_now(),
    }
    path = out / "units" / f"f{source}__to__f{target}__seed{seed}.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp"); tmp.write_text(json.dumps(payload, indent=2) + "\n")
    tmp.replace(path)
    return payload


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, nargs="+", default=[3000, 3001, 3002])
    ap.add_argument("--out", type=Path, default=Path("artifacts/natural_common_control"))
    ap.add_argument("--shard", type=int, default=0)
    ap.add_argument("--n-shards", type=int, default=1)
    ap.add_argument("--controls-only", action="store_true")
    args = ap.parse_args()

    state = load_frozen()
    pairs = [(i, j) for i in USABLE_FAMILIES for j in USABLE_FAMILIES if i != j]

    if args.controls_only:
        work = [(j, s) for j in USABLE_FAMILIES for s in args.seeds]
        for target, seed in work[args.shard::args.n_shards]:
            row = control_arm(target, seed, args.out, state)
            print(f"control N_{target} seed {seed}  families {row['control_families']}  "
                  f"hash {row['control_stream_hash']}  {row['seconds']:.0f}s", flush=True)
        return

    work = [(i, j, s) for i, j in pairs for s in args.seeds]
    for source, target, seed in work[args.shard::args.n_shards]:
        row = assemble(source, target, seed, args.out, state)
        print(f"f{source}->f{target} seed {seed}  T_aulc {row['T_aulc']:+.4f}  "
              f"head {row['head_start']:+.4f}  ctrl {row['control_stream_hash']}",
              flush=True)


if __name__ == "__main__":
    main()
